version: 0.2
phases:
  install:
    commands:
      - npm install -g serverless
      - npm install -g serverless-python-requirements
      - eval "$(pyenv init -)"
      - pyenv install 3.8.0
      - pyenv virtualenv 3.8.0 classifier@3.8.0
      - cd ./migration_manager
      - pip install -r requirements.txt
      - cd ../
      - bash build_scripts/generate_keys.sh
  build:
    commands:
      - cd ./migration_manager
      - python manage.py test
      - python manage.py migrate
      - cd ../lambdas
      - serverless deploy
