# Generated by Django 3.2.7 on 2021-09-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.IntegerField()),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'trees',
            },
        ),
    ]
