# Generated by Django 3.2.7 on 2021-09-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitingBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.IntegerField()),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_passed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fruiting_bodies',
            },
        ),
        migrations.CreateModel(
            name='FruitingBodyDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('east', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fruitingbody_east_direction_set', to='moist_chambers.fruitingbody')),
                ('north', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fruitingbody_north_direction_set', to='moist_chambers.fruitingbody')),
                ('south', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fruitingbody_south_direction_set', to='moist_chambers.fruitingbody')),
                ('west', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fruitingbody_west_direction_set', to='moist_chambers.fruitingbody')),
            ],
            options={
                'db_table': 'fruiting_body_directions',
            },
        ),
        migrations.CreateModel(
            name='Plasmodium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.IntegerField()),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_passed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'plasmodiums',
            },
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.IntegerField()),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'substrates',
            },
        ),
        migrations.CreateModel(
            name='PlasmodiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.IntegerField()),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('file_address', models.TextField()),
                ('order', models.IntegerField()),
                ('plasmodium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moist_chambers.plasmodium')),
            ],
            options={
                'db_table': 'plasmodium_images',
            },
        ),
        migrations.CreateModel(
            name='PlasmodiumDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('east', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plasmodium_east_direction_set', to='moist_chambers.plasmodium')),
                ('north', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plasmodium_north_direction_set', to='moist_chambers.plasmodium')),
                ('south', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plasmodium_south_direction_set', to='moist_chambers.plasmodium')),
                ('west', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plasmodium_west_direction_set', to='moist_chambers.plasmodium')),
            ],
            options={
                'db_table': 'plasmodium_directions',
            },
        ),
        migrations.CreateModel(
            name='MoistChamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.IntegerField()),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=16)),
                ('fruiting_bodies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moist_chambers.fruitingbodydirections')),
                ('plasmodiums', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moist_chambers.plasmodiumdirections')),
                ('substrate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moist_chambers.substrate')),
                ('tree_species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trees.tree')),
            ],
            options={
                'db_table': 'moist_chambers',
            },
        ),
        migrations.CreateModel(
            name='FruitingBodyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.IntegerField()),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('file_address', models.TextField()),
                ('order', models.IntegerField()),
                ('fruiting_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moist_chambers.fruitingbody')),
            ],
            options={
                'db_table': 'fruiting_body_images',
            },
        ),
    ]
